### ISSUE TITLE
Remove ITALICS formatting from dash_grep function

### ISSUE THREAD

**Issue by danishprakash** [prakashdanish/dash#4]
Remove ITALICS formatting from dash_grep function in the conditional block where `flag == 0`.

**Comment by anishsujanani** [comment]
I'd like to take this up if that's alright!

**Comment by danishprakash** [comment]
@asi7296 you could look at other issues, @marcosvafg is already working on this one. 
I'm unable to assign someone, I think there is something wrong with GitHub right now so sorry about that.
